
services:
  # 1. El Guardia Mágico (Traefik)
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
     
      - "8080:80" # Puerto a usar en pacheco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Le damos acceso a Docker

  frontend:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mifrontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.mifrontend.loadbalancer.server.port=80"
    depends_on:
      - backend

  # 2. El Backend Node.js
  backend:
    build: ./backend
    labels:
      - "traefik.enable=true"
      # Aquí el contenedor le dice a Traefik: "Mándame todo lo que empiece con /api"
      - "traefik.http.routers.mibackend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.mibackend.loadbalancer.server.port=3000"

  # 3. El Servidor Jenkinsservices:
# 4. El Servidor Jenkins
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      # Mantenemos el socket para que Jenkins y tu PC compartan los contenedores
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mijenkins.rule=PathPrefix(`/jenkins`)"
      - "traefik.http.services.mijenkins.loadbalancer.server.port=8080"

volumes:
  jenkins_data: